defaults:
  - data: chembl_smiles
  - model: generator
  - training: multiclass
  - override hydra/launcher: sherlock
  - _self_



global_args:
  ngpus: 1
  dtype: float32
  savedir: checkpoints
  seed: 42

  
